# The following variables can be overwritten
# variables:
    # THEME_NAME: $CI_PROJECT_TITLE # default is the project name in gitlab
    # THEME_SOURCE_DIR: '' # use 'src/' if it starts in the src dir
    # DEV_IMAGE: shopware/development:7.4-composer-2
    # MYSQL_IMAGE: 'mysql:5.7'
    # MYSQL_CMD: 'mysqld' # use $MYSQL8_CMD for mysql >= 8

variables:
    PLUGIN_DEPENDENCIES:
        value: >
            [
              { "name": "SwagCustomizedProducts", "url": "gitlab.shopware.com/shopware/6/services/customized-product", "branch": "master" },
              { "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" },
              { "name": "SwagAmazonPay", "url": "gitlab.shopware.com/shopware/6/services/swagamazonpay", "branch": "master" },
              { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "master" }
            ]
        description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'
    COMPOSER_DEPENDENCIES:
        value: >
            [
              "theiconic/name-parser",
              "amzn/amazon-pay-api-sdk-php:2.2.1"
            ]
        description: 'Additional composer dependencies. Defined in json. Example: ["theiconic/name-parser", "amzn/amazon-pay-api-sdk-php:2.2.1"]'

include:
    project: 'shopware/6/product/platform'
    ref: 'next-18865/support-plugin-deps-in-ci-templates'
    file: '.gitlab/templates/theme.yml'
