# The following variables can be overwritten
# variables:
    # PLUGIN_NAME: $CI_PROJECT_TITLE # default is the project name in gitlab
    # PLUGIN_SOURCE_DIR: 'src/' # use '' if it starts in the root dir
    # DEV_IMAGE: shopware/development:7.4-composer-2
    # MYSQL_IMAGE: 'mysql:5.7'
    # MYSQL_CMD: 'mysqld' # use $MYSQL8_CMD for mysql >= 8

include:
    project: 'shopware/6/product/platform'
    #ref: 'trunk'
    ref: 'next-17212/add-cypress-jobs-to-plugin-ci'
    file: '.gitlab/templates/plugin.yml'
