variables:
    GIT_STRATEGY: clone

include:
    project: 'shopware/6/product/platform'
    # change to trunk after merge
    ref: 'next-16981/add-ci-template-for-plugins'
    file: '.gitlab/templates/plugin.yml'

validate zip:
    allow_failure: true
